name: CI/CD

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo "IMAGE=avapolos/${GITHUB_REPOSITORY#*\/}:latest" >> $GITHUB_ENV
      - name: Dump environment variables
        run: env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
