name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_Brongar }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
        
    
    - run: |
        docker build -t ghcr.io/Brongar/moodle22/teste: latest -f Dockerfile .
        docker tag ghcr.io/Brongar/moodle22/teste: latest ghcr.io/Brongar/moodle22/teste
    - run: |
        docker push ghcr.io/Brongar/moodle22/teste: latest
        docker push ghcr.io/Brongar/moodle22/teste:${{ github.sha }}
